server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG
    org.springframework.web: DEBUG
  file:

spring:
  messages:
    basename: messages
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  http:
    log-request-details: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
file:
  upload-dir: "./upload"


#구글 앱 엔진용 설정
runtime: java
env: flex

handlers:
  url: /.*
  script: this field is required, but ignored

env_variables:
  BUCKET_NAME: mono_jung